### PR TITLE
Offload classpath filtering to gradle-plugin

### PR DESCRIPTION
**Pull request by foragerr**
closes djangofan/launch-jmeter#1

### CODE REVIEW

**Comment by djangofan** [comment]
It appears to work.   I'll take the merge and then try it again.

**Comment by djangofan** [comment]
It worked.  I just had to also edit the startJmeterWithGradle.bat  script after the build.gradle change.  Pull to get latest change and try again.

**Comment by djangofan** [comment]
Also, updated kulya plugin to version com.github.kulya:jmeter-gradle-plugin:1.3.4-2.13

**Comment by foragerr** [comment]
neat!

**Pull request merged**
